name: Maven Package
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }}/BasketBuddy # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B clean package --file BasketBuddy/pom.xml

    - name: subir fichero
      uses: actions/upload-artifact@v4
      with:
        name: allartifacts
        path: BasketBuddy/target/*

    #- name: Download artifact
     # uses: actions/download-artifact@v4
      #with:
       # name: allartifacts
        #path: distfiles


    #- name: Build Docker image
     # run: |
      #  docker build -t juanma-web .
   
    - name: Upload to remote with SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        username: juanma
        host: "157.245.42.131"
        key: ${{ secrets.KEY }}
        source: "BasketBuddy/target/*.jar"
        target: "~/"
        overwrite: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Print current directory
      run: echo "Directorio" ; pwd

    - name: Deploy to digitalocean
      uses: appleboy/ssh-action@master
      with:
        username: juanma
        host: "157.245.42.131"
        key: ${{ secrets.KEY }}
        script: |
            docker stop juanma-web-1 || true
            docker rm juanma-web-1 || true
            docker rmi juanma-web || true
            cd ~/ && docker-compose up -d
